#!/bin/sh

case "$1" in
  start)
    
    start-stop-daemon -S -n aesdchar_load -a /usr/bin/aesdchar_load
    ;;
    stop)
    
    start-stop-daemon -S -n aesdchar_unload -a /usr/bin/aesdchar_unload
    ;;
  *)
    echo "Usage: $0 {start|stop}"
  exit 1
esac

exit 0
